-- ============================================================
-- 002 - Catalogo de codigo de baixa (166 codigos)
--
-- Origem: GUIA_CODIGO_BAIXAv4 2026, oficial da CLARO.
--
-- 'familia' vem do guia. 'natureza' e 'responsabilidade' NAO vem:
-- sao nossas, e sao o que permite responder a pergunta que o ngestor
-- nao responde -- "desta improdutiva, quanto e culpa nossa?".
--
--   natureza        SUCESSO | IMPRODUTIVA | CANCELAMENTO | REAGENDAMENTO
--   responsabilidade CLIENTE | REDE | OPERADORA | TECNICO | TERCEIRO
--
-- revisar = true nos 6 codigos onde a classificacao e discutivel e
-- precisa da validacao do Emanuel. Ver docs/05-CODIGOS-A-VALIDAR.md
-- ============================================================

create table codigo_baixa (
  id         uuid primary key default uuid_generate_v4(),
  codigo     integer not null unique,
  descricao  text not null,
  familia    text not null,
  natureza   text not null
             check (natureza in ('SUCESSO','IMPRODUTIVA','CANCELAMENTO','REAGENDAMENTO','INDEFINIDA')),
  responsabilidade text
             check (responsabilidade in ('CLIENTE','REDE','OPERADORA','TECNICO','TERCEIRO')),
  revisar    boolean not null default false,
  ativo      boolean not null default true,
  -- um sucesso nao tem culpado
  constraint sucesso_sem_responsavel
    check (natureza <> 'SUCESSO' or responsabilidade is null)
);
create index on codigo_baixa (natureza);
create index on codigo_baixa (familia);

insert into codigo_baixa (codigo, descricao, familia, natureza, responsabilidade, revisar) values
  (2, 'Apoio Cancelado', 'ADMINISTRATIVO', 'CANCELAMENTO', null, false),
  (39, 'Cancelado (código 39)', 'CANCELADO', 'CANCELAMENTO', null, false),
  (40, 'Cancelado (código 40)', 'CANCELADO', 'CANCELAMENTO', null, false),
  (41, 'Cancelado (código 41)', 'CANCELADO', 'CANCELAMENTO', null, false),
  (42, 'Cancelado (código 42)', 'CANCELADO', 'CANCELAMENTO', null, false),
  (100, 'Agendamento Não Cumprido', 'IMPRODUTIVO', 'IMPRODUTIVA', 'TECNICO', false),
  (101, 'Endereço Não Localizado', 'IMPRODUTIVO', 'IMPRODUTIVA', 'CLIENTE', false),
  (103, 'Chuva', 'IMPRODUTIVO', 'IMPRODUTIVA', 'TERCEIRO', false),
  (104, 'Falta de Material', 'IMPRODUTIVO', 'IMPRODUTIVA', 'TECNICO', false),
  (105, 'Sem Energia Elétrica Na Região / Prédio / Residência', 'IMPRODUTIVO', 'IMPRODUTIVA', 'TERCEIRO', false),
  (106, 'Cliente Ausente', 'IMPRODUTIVO', 'IMPRODUTIVA', 'CLIENTE', false),
  (107, 'Entrada Não Autorizada', 'IMPRODUTIVO', 'IMPRODUTIVA', 'CLIENTE', false),
  (108, 'Tubulação Obstruída sem solução', 'IMPRODUTIVO', 'IMPRODUTIVA', 'CLIENTE', false),
  (109, 'Pagamento Apresentado', 'RETIRADA', 'CANCELAMENTO', null, true),
  (110, 'Problema Na Tubulação', 'IMPRODUTIVO', 'IMPRODUTIVA', 'CLIENTE', false),
  (111, 'Reagendamento Solicitado Pelo Cliente', 'IMPRODUTIVO', 'REAGENDAMENTO', 'CLIENTE', false),
  (112, 'Sem Acesso Ao DG / Sótão', 'IMPRODUTIVO', 'IMPRODUTIVA', 'CLIENTE', false),
  (113, 'Sem TV / Computador na Residencia / Celular', 'IMPRODUTIVO', 'IMPRODUTIVA', 'CLIENTE', false),
  (118, 'Cancelado (código 118)', 'CANCELADO', 'CANCELAMENTO', null, false),
  (120, 'Impossibilidade ao Atendimento', 'IMPRODUTIVO', 'IMPRODUTIVA', 'TERCEIRO', true),
  (125, 'Cliente desiste da Agenda', 'IMPRODUTIVO', 'IMPRODUTIVA', 'CLIENTE', false),
  (126, 'Situação Pontual de Risco', 'IMPRODUTIVO', 'IMPRODUTIVA', 'TERCEIRO', false),
  (127, 'Área de Risco Bloqueio de Endereço', 'IMPRODUTIVO', 'IMPRODUTIVA', 'TERCEIRO', false),
  (202, 'Node em Outage', 'IMPRODUTIVO', 'IMPRODUTIVA', 'REDE', false),
  (203, 'Rede Externa Com Problema', 'IMPRODUTIVO', 'IMPRODUTIVA', 'REDE', false),
  (204, 'Backbone Com Problema', 'IMPRODUTIVO', 'IMPRODUTIVA', 'REDE', false),
  (205, 'Falta Tap Ou Passivo / Tap Ou Passivo Lotado', 'IMPRODUTIVO', 'IMPRODUTIVA', 'REDE', false),
  (206, 'Prédio Sem Backbone', 'IMPRODUTIVO', 'IMPRODUTIVA', 'REDE', false),
  (207, 'Prédio Sem Retorno Ativado', 'IMPRODUTIVO', 'IMPRODUTIVA', 'REDE', false),
  (208, 'Problemas no NOW', 'IMPRODUTIVO', 'IMPRODUTIVA', 'OPERADORA', false),
  (209, 'NAP Lotada em MDU', 'IMPRODUTIVO', 'IMPRODUTIVA', 'REDE', false),
  (211, 'Falta NAP/NAP Lotada', 'IMPRODUTIVO', 'IMPRODUTIVA', 'REDE', false),
  (217, 'BACKBONE GPON COM PROBLEMA', 'IMPRODUTIVO', 'IMPRODUTIVA', 'REDE', false),
  (301, 'Tipo de OS Incorreta', 'IMPRODUTIVO', 'IMPRODUTIVA', 'OPERADORA', false),
  (302, 'Desistência da Assinatura / Serviço', 'IMPRODUTIVO', 'IMPRODUTIVA', 'CLIENTE', false),
  (303, 'Forma de Instalação Não Aceita Pelo Cliente', 'IMPRODUTIVO', 'IMPRODUTIVA', 'CLIENTE', false),
  (304, 'Node Nao Liberado (Para Virtua e/ou Net Fone)', 'IMPRODUTIVO', 'IMPRODUTIVA', 'REDE', false),
  (305, 'Rua não cabeada', 'IMPRODUTIVO', 'IMPRODUTIVA', 'REDE', false),
  (306, 'Não Reside No Endereço', 'IMPRODUTIVO', 'IMPRODUTIVA', 'CLIENTE', false),
  (307, 'Residência Em Construção / Reforma', 'IMPRODUTIVO', 'IMPRODUTIVA', 'CLIENTE', false),
  (308, 'Instalação Não Contemplara Padrão', 'IMPRODUTIVO', 'IMPRODUTIVA', 'CLIENTE', false),
  (309, 'Computador não possui configuração Minima', 'IMPRODUTIVO', 'IMPRODUTIVA', 'CLIENTE', false),
  (312, 'Cliente não solicitou serviço', 'IMPRODUTIVO', 'IMPRODUTIVA', 'OPERADORA', false),
  (316, 'Rua não cabeada GPON', 'IMPRODUTIVO', 'IMPRODUTIVA', 'REDE', false),
  (400, 'Correção de Cadastro', 'IMPRODUTIVO', 'IMPRODUTIVA', 'OPERADORA', false),
  (402, 'Divergência de Dados Cadastrais', 'IMPRODUTIVO', 'IMPRODUTIVA', 'OPERADORA', false),
  (404, 'Cliente Recusa-se Devolver O Decoder / Cable Modem', 'RETIRADA', 'IMPRODUTIVA', 'CLIENTE', false),
  (408, 'Equipamento do Cliente com Defeito', 'IMPRODUTIVO', 'IMPRODUTIVA', 'CLIENTE', false),
  (409, 'INSTALAÇÃO EFETUADA', 'MESH', 'SUCESSO', null, false),
  (428, 'Desconexao Efetuada Com Retirada De Equipamento', 'RETIRADA', 'SUCESSO', null, false),
  (429, 'Desconexao Efetuada Sem Retirada De Equipamento', 'RETIRADA', 'SUCESSO', null, false),
  (430, 'Equipamento Retirado', 'RETIRADA', 'SUCESSO', null, false),
  (466, 'ORCAMENTO RETIRADO', 'VISTORIA', 'SUCESSO', null, false),
  (468, 'CASO PROCEDENTE RESOLVIDO DURANTE A VISTORIA', 'VISTORIA', 'SUCESSO', null, false),
  (469, 'CASO INDEFINIDO', 'VISTORIA', 'IMPRODUTIVA', 'TERCEIRO', true),
  (470, 'CASO IMPROCEDENTE', 'VISTORIA', 'SUCESSO', null, true),
  (471, 'RECONFIGURAÇÃO DO SSID/SENHA WIFI', 'MESH', 'SUCESSO', null, false),
  (472, 'INSTRUÇÕES DE USO DO EQUIPAMENTO - EXTENSOR', 'MESH', 'SUCESSO', null, false),
  (473, 'NECESSIDADE DE INSTALAÇÃO VIA CABO ETHERNET', 'MESH', 'IMPRODUTIVA', 'CLIENTE', true),
  (474, 'REPOSICIONADO O EXTENSOR', 'MESH', 'SUCESSO', null, false),
  (475, 'VELOCIDADE DO EXTENSOR- CONFORME CONTRATADA', 'MESH', 'SUCESSO', null, false),
  (476, 'RECONFIGURADO / PAREAMENTO EXTENSORES', 'MESH', 'SUCESSO', null, false),
  (477, 'INSTALAÇÃO MESH CABEADA', 'MESH', 'SUCESSO', null, false),
  (478, 'Configuração Concluída', 'RECONFIGURACAO', 'SUCESSO', null, false),
  (483, 'TROCA DE EXTENSOR MESH TRAVADO', 'MESH', 'SUCESSO', null, false),
  (484, 'TROCA DE EXTENSOR MESH QUEIMADO', 'MESH', 'SUCESSO', null, false),
  (499, 'Desconexao por Risco de Subscricao', 'RETIRADA', 'SUCESSO', null, false),
  (500, 'Readequação De Sinal - Passivos', 'SINAL', 'SUCESSO', null, false),
  (501, 'Amplificador Equalizado', 'SINAL', 'SUCESSO', null, false),
  (502, 'Amplificador Com Defeito - Troca', 'SINAL', 'SUCESSO', null, false),
  (503, 'Amplificador Queimado - Troca', 'SINAL', 'SUCESSO', null, false),
  (504, 'Instalação de Amplificador', 'SINAL', 'SUCESSO', null, false),
  (505, 'Passivo Interno Queim./Degrad. - Troca', 'PASSIVO', 'SUCESSO', null, false),
  (506, 'Passivo Interno Fora Do Padrão - Troca', 'PASSIVO', 'SUCESSO', null, false),
  (507, 'Passivo MDU Queim./Degrad. - Troca', 'PASSIVO', 'SUCESSO', null, false),
  (508, 'Passivo MDU Fora Do Padrão - Troca', 'PASSIVO', 'SUCESSO', null, false),
  (509, 'Cable Isolator Danificado/Queimado - Troca', 'PASSIVO', 'SUCESSO', null, false),
  (510, 'Fonte Com Defeito - Troca', 'EQUIPAMENTO', 'SUCESSO', null, false),
  (511, 'Controle Remoto/Danificado/Extraviado - Troca', 'EQUIPAMENTO', 'SUCESSO', null, false),
  (512, 'Controle Remoto Com Defeito - Troca', 'EQUIPAMENTO', 'SUCESSO', null, false),
  (513, 'Incompatibilidade Da Tecnologia / TV', 'EQUIPAMENTO', 'SUCESSO', null, false),
  (514, 'Envio De Hit - Habilitar Canais', 'EQUIPAMENTO', 'SUCESSO', null, false),
  (515, 'Envio De Hit - Correção Do Update ID', 'EQUIPAMENTO', 'SUCESSO', null, false),
  (516, 'T.T - Travado', 'EQUIPAMENTO', 'SUCESSO', null, false),
  (517, 'T.T - Queimado', 'EQUIPAMENTO', 'SUCESSO', null, false),
  (518, 'T.T - Não Habilita / Não Sincroniza', 'EQUIPAMENTO', 'SUCESSO', null, false),
  (519, 'T.T - Não Grava', 'EQUIPAMENTO', 'SUCESSO', null, false),
  (520, 'T.T - Não Atualiza SW', 'EQUIPAMENTO', 'SUCESSO', null, false),
  (521, 'T.T - Intermitente', 'EQUIPAMENTO', 'SUCESSO', null, false),
  (522, 'T.T - IN / OUT Queimadas', 'EQUIPAMENTO', 'SUCESSO', null, false),
  (523, 'T.T - Alcance Wifi', 'EQUIPAMENTO', 'SUCESSO', null, false),
  (524, 'T.T - Solic. Cliente', 'EQUIPAMENTO', 'SUCESSO', null, false),
  (525, 'T.T - Falha em Imagem/Quadriculando', 'EQUIPAMENTO', 'SUCESSO', null, false),
  (526, 'T.T - Erro de Leitura Smart', 'EQUIPAMENTO', 'SUCESSO', null, false),
  (527, 'T.T - Não Navega', 'EQUIPAMENTO', 'SUCESSO', null, false),
  (528, 'T.T – Problema de falha no Áudio', 'EQUIPAMENTO', 'SUCESSO', null, false),
  (529, 'T.T – Modelo não Compatível', 'EQUIPAMENTO', 'SUCESSO', null, false),
  (530, 'T.T Por Outro Colocado No Mesmo Serviço', 'EQUIPAMENTO', 'SUCESSO', null, false),
  (531, 'Smart Que Não Habilita - Troca', 'EQUIPAMENTO', 'SUCESSO', null, false),
  (532, 'Smart com Tela Preta - Troca', 'EQUIPAMENTO', 'SUCESSO', null, false),
  (533, 'Reset Na Config Terminal - Travado', 'RECONFIGURACAO', 'SUCESSO', null, false),
  (534, 'Reset Na Config Terminal - Solicit Senha', 'RECONFIGURACAO', 'SUCESSO', null, false),
  (535, 'Reset Na Config Terminal - Não Atualiza', 'RECONFIGURACAO', 'SUCESSO', null, false),
  (536, 'Reconfigurado Roteador do cliente', 'RECONFIGURACAO', 'SUCESSO', null, false),
  (537, 'Reconfigurado eMTA/Roteador NET-WIFI', 'RECONFIGURACAO', 'SUCESSO', null, false),
  (538, 'Reconfiguração Do Formato Da Imagem', 'RECONFIGURACAO', 'SUCESSO', null, false),
  (539, 'Reconfiguração De Audio', 'RECONFIGURACAO', 'SUCESSO', null, false),
  (540, 'Conector Interno Oxidado - Troca', 'CONEXOES', 'SUCESSO', null, false),
  (541, 'Conector Interno Mal Feito - Troca', 'CONEXOES', 'SUCESSO', null, false),
  (542, 'Conector Interno Fora Do Padrão - Troca', 'CONEXOES', 'SUCESSO', null, false),
  (543, 'Conector TAP Oxidado - Troca', 'CONEXOES', 'SUCESSO', null, false),
  (544, 'Conector TAP Mal Feito - Troca', 'CONEXOES', 'SUCESSO', null, false),
  (545, 'Conector TAP - Fora Do Padrão - Troca', 'CONEXOES', 'SUCESSO', null, false),
  (546, 'Conector MDU Oxidado - Troca', 'CONEXOES', 'SUCESSO', null, false),
  (547, 'Conector MDU Mal feito - Troca', 'CONEXOES', 'SUCESSO', null, false),
  (548, 'Conector MDU Fora Do Padrão - Troca', 'CONEXOES', 'SUCESSO', null, false),
  (549, 'Velocidade Do Virtua Conforme Contratada', 'CLIENTE', 'SUCESSO', null, false),
  (550, 'Canal Não Pertece Ao Pacote Contratado', 'CLIENTE', 'SUCESSO', null, false),
  (551, 'Sintonia Efetuada – AV/HDMI', 'CLIENTE', 'SUCESSO', null, false),
  (552, 'Instruções Do Uso Da Interatividade', 'CLIENTE', 'SUCESSO', null, false),
  (553, 'Instruções De Uso Do Controle Remoto', 'CLIENTE', 'SUCESSO', null, false),
  (554, 'Instruções Sobre Smart Card', 'CLIENTE', 'SUCESSO', null, false),
  (555, 'Sem Defeito No Produto Virtua Reclamado', 'CLIENTE', 'SUCESSO', null, false),
  (556, 'Sem Defeito No Produto TV Reclamado', 'CLIENTE', 'SUCESSO', null, false),
  (557, 'Sem Defeito No Produto Netfone Reclamado', 'CLIENTE', 'SUCESSO', null, false),
  (558, 'Boot No Terminal', 'CLIENTE', 'SUCESSO', null, false),
  (559, 'Computador Reconfigurado', 'CLIENTE', 'SUCESSO', null, false),
  (560, 'Equipamento / Rede De Dados Com Defeito', 'CLIENTE', 'SUCESSO', null, false),
  (561, 'Ponto Sem Cadastro Não Regularizado', 'CLIENTE', 'IMPRODUTIVA', 'OPERADORA', false),
  (562, 'Cabo Reconectado/Identificado', 'CABEAMENTO', 'SUCESSO', null, false),
  (563, 'Reconexão Dos Cabos No Equipamento Do Cliente', 'CABEAMENTO', 'SUCESSO', null, false),
  (564, 'Cabos Especiais Com Defeito - Troca', 'CABEAMENTO', 'SUCESSO', null, false),
  (565, 'Entrega De Cabos Especiais', 'CABEAMENTO', 'SUCESSO', null, false),
  (566, 'Drop Refeito', 'CABEAMENTO', 'SUCESSO', null, false),
  (567, 'Cabeamento Coaxial Refeito', 'CABEAMENTO', 'SUCESSO', null, false),
  (568, 'Cabeamento Telefônico Refeito', 'CABEAMENTO', 'SUCESSO', null, false),
  (569, 'Necessário Refazer Cabeamento Telefônico', 'CABEAMENTO', 'IMPRODUTIVA', 'REDE', false),
  (570, 'Necessário Refazer Cabeamento Coaxial', 'CABEAMENTO', 'IMPRODUTIVA', 'REDE', false),
  (571, 'Encaminhado À Embratel', 'INFRAESTRUTURA', 'IMPRODUTIVA', 'TERCEIRO', false),
  (572, 'Problema Identificado No Circuito De Video', 'INFRAESTRUTURA', 'IMPRODUTIVA', 'REDE', false),
  (573, 'Data Center / Headend Com Problema', 'INFRAESTRUTURA', 'IMPRODUTIVA', 'OPERADORA', false),
  (574, 'Correção efetuada no Data Center', 'INFRAESTRUTURA', 'SUCESSO', null, false),
  (575, 'Tomada Telefone Com Problema - Troca', 'TELEFONIA', 'SUCESSO', null, false),
  (576, 'Distribuidor ''T'' Com Problema - Troca', 'TELEFONIA', 'SUCESSO', null, false),
  (577, 'Conector RJ11 Oxidado - Troca', 'TELEFONIA', 'SUCESSO', null, false),
  (578, 'Conector RJ11 Mal Feito - Troca', 'TELEFONIA', 'SUCESSO', null, false),
  (579, 'Limpeza De Ruído Executada', 'MANUTENCAO MDU', 'SUCESSO', null, false),
  (580, 'Conexões De Rede De Dados Refeitas', 'MANUTENCAO MDU', 'SUCESSO', null, false),
  (581, 'Cabeamento De Rede De Dados Refeito', 'MANUTENCAO MDU', 'SUCESSO', null, false),
  (582, 'Roteador Com Problema', 'MANUTENCAO MDU', 'IMPRODUTIVA', 'CLIENTE', true),
  (583, 'NECESSÁRIO REFAZER CABEAMENTO ÓPTICO', 'GPON', 'IMPRODUTIVA', 'REDE', false),
  (584, 'CONECTOR ÓPTICO INTERNO DANIFICADO - TROCA', 'GPON', 'SUCESSO', null, false),
  (585, 'TROCA DE PAINEL', 'MANUTENCAO MDU', 'SUCESSO', null, false),
  (586, 'TROCA DE SENSOR', 'MANUTENCAO MDU', 'SUCESSO', null, false),
  (587, 'TROCA DE CAMERA', 'MANUTENCAO MDU', 'SUCESSO', null, false),
  (588, 'CONECTOR ÓPTICO MDU/DIO DANIFICADO - TROCA', 'GPON', 'SUCESSO', null, false),
  (589, 'CONECTOR ÓPTICO REDE EXTERNA NAP DANIFICADO - TROCA', 'GPON', 'SUCESSO', null, false),
  (590, 'PTO COM DEFEITO TROCA', 'GPON', 'SUCESSO', null, false),
  (591, 'PATCH CORD COM DEFEITO TROCA', 'GPON', 'SUCESSO', null, false),
  (594, 'Reconfiguração Da Senha Wifi', 'RECONFIGURACAO', 'SUCESSO', null, false),
  (597, 'Troca de Pilha', 'CLIENTE', 'SUCESSO', null, false),
  (599, 'Refazer Cabeamento BSOD', 'CABEAMENTO', 'SUCESSO', null, false),
  (603, 'Cancelado por Ativo / Rede Externa com Problema', 'IMPRODUTIVO', 'IMPRODUTIVA', 'REDE', false),
  (800, 'Desatribuído', 'ADMINISTRATIVO', 'CANCELAMENTO', null, false),
  (815, 'ENVIO DE CHIP VIA CORREIO', 'RETIRADA', 'SUCESSO', null, false),
  (910, 'MDU GPON EXISTENTE', 'GPON', 'SUCESSO', null, false);

-- Conferencia rapida apos rodar:
--   select natureza, count(*) from codigo_baixa group by natureza;
--   select * from codigo_baixa where revisar;
